# Source of India LaTeX Project Configuration
# Configuration file for the SoI LaTeX document class

# Build and Compilation Settings
build:
  # LaTeX engine selection (xelatex, lualatex, pdflatex)
  compiler: xelatex
  
  # Font configuration
  font: libertinus  # libertinus, lmodern, times
  
  # Paper size configuration
  page_size: a4  # a4, a5
  
  # Base font size
  font_size: 12  # 10, 11, 12
  
  # Document mode
  mode: final  # draft, final
  
  # Number of compilation passes
  passes: 2

# Document Structure Settings
document:
  # Amendment display control
  show_amendment_footnotes: true
  
  # Article number validation
  validate_article_numbers: true
  
  # Automatic cross-reference generation
  auto_cross_reference: true
  
  # Include table of contents
  include_toc: true
  
  # Include cover page
  include_cover: true
  
  # Include preamble
  include_preamble: true

# Output Configuration
output:
  # PDF bookmarks/navigation
  pdf_bookmarks: true
  
  # Hyperlinks in PDF
  hyperlinks: true
  
  # Output directory
  directory: output
  
  # File naming convention
  filename_format: "constitution-{page_size}-{font_size}pt"
  
  # Keep auxiliary files
  keep_aux_files: false

# Content Settings
content:
  # Parts to include (list of part numbers)
  include_parts:
    - I    # The Union and its Territory
    - II   # Citizenship
    - III  # Fundamental Rights
    - IV   # Directive Principles of State Policy
    - V    # The Union
    - VI   # The States
    - VII  # States in the B Part of the First Schedule (Repealed)
    - VIII # The Union Territories
    - IX   # The Panchayats
    - IXA  # The Municipalities
    - IXB  # The Co-operative Societies
    - X    # The Scheduled and Tribal Areas
    - XI   # Relations between the Union and the States
    - XII  # Finance, Property, Contracts and Suits
    - XIII # Trade, Commerce and Intercourse
    - XIV  # Services Under the Union and the States
    - XIVA # Tribunals
    - XV   # Elections
    - XVI  # Special Provisions Relating to Certain Classes
    - XVII # Official Language
    - XVIII # Emergency Provisions
    - XIX  # Miscellaneous
    - XX   # Amendment of the Constitution
    - XXI  # Temporary, Transitional and Special Provisions
    - XXII # Short Title, Commencement, Authoritative Text in Hindi and Repeals
  
  # Schedules to include (list of schedule numbers)
  include_schedules:
    - 1   # States and Union Territories
    - 2   # Provisions as to the President and the Governors of States
    - 3   # Forms of Oaths or Affirmations
    - 4   # Allocation of seats in the Council of States
    - 5   # Provisions as to the Administration and Control of Scheduled Areas and Scheduled Tribes
    - 6   # Provisions as to the Administration of Tribal Areas in the States of Assam, Meghalaya, Tripura and Mizoram
    - 7   # Union List, State List and Concurrent List
    - 8   # Languages
    - 9   # Validation of certain Acts and Regulations
    - 10  # Provisions as to disqualification on ground of defection
    - 11  # Powers, authority and responsibilities of Panchayats
    - 12  # Powers, authority and responsibilities of Municipalities
  
  # Amendment cutoff date (YYYY-MM-DD)
  # Only amendments up to this date will be included
  amendment_cutoff_date: "2023-12-31"

# Development and Testing
development:
  # Enable debug mode
  debug: false
  
  # Verbose output
  verbose: false
  
  # Generate test documents
  generate_tests: true
  
  # Validate structure before compilation
  validate_structure: true
  
  # Check for missing articles
  check_missing_articles: true

# Advanced Settings
advanced:
  # Custom LaTeX packages to load
  additional_packages: []
  
  # Custom macros file
  custom_macros_file: ""
  
  # Memory allocation for LaTeX
  max_memory: "5000000"
  
  # Enable shell escape (for advanced features)
  shell_escape: false
  
  # Custom font paths (for XeLaTeX/LuaLaTeX)
  font_paths: []

# Localization Settings
localization:
  # Primary language
  language: english
  
  # Text direction (ltr, rtl)
  text_direction: ltr
  
  # Number format (western, devanagari)
  number_format: western
  
  # Date format
  date_format: "YYYY-MM-DD"

# Quality Control
quality:
  # Maximum line length for text wrapping
  max_line_length: 80
  
  # Orphan and widow control
  orphan_penalty: 10000
  widow_penalty: 10000
  
  # Enable microtype for better typography
  enable_microtype: true
  
  # Strict mode (fail on warnings)
  strict_mode: false

# File Management
files:
  # Article file naming pattern
  article_pattern: "includes/articles/article-{number}.tex"
  
  # Part file naming pattern
  part_pattern: "includes/parts/part-{number}.tex"
  
  # Schedule file naming pattern
  schedule_pattern: "includes/schedules/schedule-{number}.tex"
  
  # Backup original files before modification
  backup_files: true
  
  # Backup directory
  backup_directory: "backups"